version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "water-management"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j8jgzrngjsm8"
s3_prefix = "water-management"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
image_repositories = []
